import = ["~/.config/alacritty/themes/alacritty-theme/themes/rose-pine.toml"]

live_config_reload = true

[shell]
program = "/usr/local/bin/zsh"
args = ["-l", "-c", "tmux a -t 0 || tmux "]

[env]
TERM = "xterm-256color"

[window]
dimensions = {columns = 300, lines = 200}
startup_mode = "Maximized"
dynamic_title = true
opacity = 0.95
blur = true

padding = {x = 10, y = 0}
decorations = "Buttonless"

[scrolling]
history = 5000

[mouse]
hide_when_typing = true

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 15
offset = {x = 1, y = 1}

[font.normal]
family = "PlemolJP Console NF"

[font.bold]
family = "PlemolJP Console NF"

[font.bold_italic]
family = "PlemolJP Console NF"
style = "Italic"

[font.italic]
family = "PlemolJP Console NF"
style = "Italic"

[keyboard]
bindings = [
	{key="i", mods="Command", action="ToggleViMode"},
	{key="PageUp", action="ScrollLineUp"},
	{key="PageDown", action="ScrollLineDown"},
]
